---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn lint
  - yarn workspace @milestones/core test
  - yarn workspace @milestones/babel-plugin-strip-milestones test
  - yarn build
  - yarn workspace @milestones/ember test
  - env STRIP_MILESTONES=true yarn workspace @milestones/ember test
  - yarn workspace @milestones/ember add ember-concurrency@latest --dev
  - yarn workspace @milestones/ember test
